spring.application.name=sb_employee_app

# Set log level
logging.level.root=INFO

# Show SQL logs (optional)
logging.level.org.springframework.jdbc.core=DEBUG

# Custom log format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

 # TRACE DEBUG INFO WARN ERROR OFF

#logging.level.root=OFF
#logging.level.com.priya=TRACE
#logging.file.name=logs/app.log

